insert into inv_db.man_paginas_t (id_pagina,id_maestro,tipo,titulo,secuencia,documentacion,plural,singular,campo_id,campo_descripcion,condicion_solo_lectura,ordenar_por,ordenar_dir,consultar,agregar,modificar,borrar,javascript,id_permiso_consultar,id_permiso_agregar,id_permiso_modificar,id_permiso_borrar,imprimir,descargar,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro,pendientes_sql,pendientes_titulo,campos_unicos,autorefrescar,mensaje_solo_lectura,opcion_menu,cerrar_al_guardar) values (
'22',
null,
'E',
'Perfil del usuario',
'1',
null,
'Perfil',
'Perfil',
'id_usuario',
'descripcion_usuario',
null,
'nombre_usuario',
'ASC',
'select * from inv_db.seg_perfil_v where id_usuario= :ID_USUARIO',
null,
'inv_db.seg_perfil_pkg.modificar',
null,
null,
null,
null,
null,
null,
'N',
'N',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A',
null,
null,
'id_usuario',
null,
null,
'Perfil del usuario',
'S')
;
insert into inv_db.man_paginas_t (id_pagina,id_maestro,tipo,titulo,secuencia,documentacion,plural,singular,campo_id,campo_descripcion,condicion_solo_lectura,ordenar_por,ordenar_dir,consultar,agregar,modificar,borrar,javascript,id_permiso_consultar,id_permiso_agregar,id_permiso_modificar,id_permiso_borrar,imprimir,descargar,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro,pendientes_sql,pendientes_titulo,campos_unicos,autorefrescar,mensaje_solo_lectura,opcion_menu) values (
'71',
null,
'M',
'Buzón de Mensajes',
'1',
null,
'Mensajes',
'Mensaje',
'ID_BUZON_MENSAJE',
'ASUNTO',
null,
'ENVIADO_EN',
'DESC',
'select * from inv_db.seg_buzon_mensajes_v where id_usuario= :ID_USUARIO',
null,
null,
'inv_db.seg_buzon_mensajes_pkg.borrar',
null,
null,
null,
null,
null,
'N',
'N',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A',
null,
null,
'ID_BUZON_MENSAJE',
null,
null,
'Buzón de Mensajes')
;
insert into inv_db.man_paginas_t (id_pagina,id_maestro,tipo,titulo,secuencia,documentacion,plural,singular,campo_id,campo_descripcion,condicion_solo_lectura,ordenar_por,ordenar_dir,consultar,agregar,modificar,borrar,javascript,id_permiso_consultar,id_permiso_agregar,id_permiso_modificar,id_permiso_borrar,imprimir,descargar,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro,pendientes_sql,pendientes_titulo,campos_unicos,autorefrescar,mensaje_solo_lectura,opcion_menu) values (
'110',
null,
'M',
'Roles del Sistema',
'1',
null,
'Roles',
'Rol',
'id_rol',
'rol',
null,
'rol',
'ASC',
'inv_db.seg_roles_v',
'inv_db.seg_roles_pkg.agregar',
'inv_db.seg_roles_pkg.modificar',
'inv_db.seg_roles_pkg.borrar',
null,
'3277',
'3280',
'3281',
'3276',
'N',
'N',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A',
null,
null,
'rol',
null,
null,
'Roles del Sistema')
;
insert into inv_db.man_paginas_t (id_pagina,id_maestro,tipo,titulo,secuencia,documentacion,plural,singular,campo_id,campo_descripcion,condicion_solo_lectura,ordenar_por,ordenar_dir,consultar,agregar,modificar,borrar,javascript,id_permiso_consultar,id_permiso_agregar,id_permiso_modificar,id_permiso_borrar,imprimir,descargar,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro,pendientes_sql,pendientes_titulo,campos_unicos,autorefrescar,mensaje_solo_lectura,opcion_menu) values (
'113',
'110',
'M',
'Permisos por Rol del Sistema',
'1',
null,
'Permisos',
'Permiso',
'id_registro',
'permiso',
null,
'permiso',
'ASC',
'inv_db.seg_det_permisos_roles_v',
'inv_db.seg_det_permisos_roles_pkg.agregar',
'inv_db.seg_det_permisos_roles_pkg.modificar',
'inv_db.seg_det_permisos_roles_pkg.borrar',
null,
'3882',
'3880',
'3883',
null,
'N',
'N',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A',
'select id_rol	 maestro

     , null	registro

     , rol	descripcion

from inv_db.seg_roles_t a

where not exists (

  select 1 from inv_db.seg_det_permisos_roles_t d 

  where d.id_rol = a.id_rol

)',
'Roles sin permisos asignados',
'id_registro',
null,
null,
'Permisos por Rol del Sistema')
;
insert into inv_db.man_paginas_t (id_pagina,id_maestro,tipo,titulo,secuencia,documentacion,plural,singular,campo_id,campo_descripcion,condicion_solo_lectura,ordenar_por,ordenar_dir,consultar,agregar,modificar,borrar,javascript,id_permiso_consultar,id_permiso_agregar,id_permiso_modificar,id_permiso_borrar,imprimir,descargar,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro,pendientes_sql,pendientes_titulo,campos_unicos,autorefrescar,mensaje_solo_lectura,opcion_menu) values (
'114',
'110',
'M',
'Usuarios por Rol del Sistema',
'2',
null,
'Usuarios',
'Usuario en rol',
'id_rol_usuario',
'id_usuario',
null,
'id_usuario',
'ASC',
'inv_db.seg_det_roles_usuarios_v',
'inv_db.seg_det_roles_usuarios_pkg.agregar',
'inv_db.seg_det_roles_usuarios_pkg.modificar',
'inv_db.seg_det_roles_usuarios_pkg.borrar',
null,
'3899',
'3898',
'3897',
'3896',
'N',
'N',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A',
null,
null,
'id_rol-id_usuario',
null,
null,
'Usuarios por Rol del Sistema')
;
insert into inv_db.man_paginas_t (id_pagina,id_maestro,tipo,titulo,secuencia,documentacion,plural,singular,campo_id,campo_descripcion,condicion_solo_lectura,ordenar_por,ordenar_dir,consultar,agregar,modificar,borrar,javascript,id_permiso_consultar,id_permiso_agregar,id_permiso_modificar,id_permiso_borrar,imprimir,descargar,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro,pendientes_sql,pendientes_titulo,campos_unicos,autorefrescar,mensaje_solo_lectura,opcion_menu) values (
'115',
null,
'M',
'Usuarios del Sistema',
'1',
null,
'Usuarios',
'Usuario',
'id_usuario',
'id_usuario',
null,
'id_usuario',
'ASC',
'inv_db.seg_usuarios_v',
'inv_db.seg_usuarios_pkg.agregar',
'inv_db.seg_usuarios_pkg.modificar',
null,
'  if ($(''input[id="TXT_ADMINISTRADOR_S"]:checked'').length > 0) {

    $("#TR_ROLES").hide();

  } else {

    $("#TR_ROLES").show();

  }

  $("#TXT_ADMINISTRADOR_S").click(function(){

    $("#TR_ROLES").hide();

  });

  $("#TXT_ADMINISTRADOR_N").click(function(){

    $("#TR_ROLES").show();

  });	   ',
'3981',
'3978',
'3979',
null,
'N',
'N',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A',
null,
null,
'id_usuario',
null,
null,
'Usuarios del Sistema')
;
insert into inv_db.man_paginas_t (id_pagina,id_maestro,tipo,titulo,secuencia,documentacion,plural,singular,campo_id,campo_descripcion,condicion_solo_lectura,ordenar_por,ordenar_dir,consultar,agregar,modificar,borrar,javascript,id_permiso_consultar,id_permiso_agregar,id_permiso_modificar,id_permiso_borrar,imprimir,descargar,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro,pendientes_sql,pendientes_titulo,campos_unicos,autorefrescar,mensaje_solo_lectura,opcion_menu) values (
'116',
null,
'M',
'Trazabilidad de cambios',
'1',
null,
'Trazabilidad de cambios',
'Cambios',
'id_trazabilidad',
'id_trazabilidad',
null,
'id_trazabilidad',
'DESC',
'inv_db.man_trazabilidad_v',
null,
null,
null,
null,
'4177',
null,
null,
null,
'N',
'N',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A',
null,
null,
null,
null,
null,
'Trazabilidad de cambios')
;
insert into inv_db.man_paginas_t (id_pagina,id_maestro,tipo,titulo,secuencia,documentacion,plural,singular,campo_id,campo_descripcion,condicion_solo_lectura,ordenar_por,ordenar_dir,consultar,agregar,modificar,borrar,javascript,id_permiso_consultar,id_permiso_agregar,id_permiso_modificar,id_permiso_borrar,imprimir,descargar,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro,pendientes_sql,pendientes_titulo,campos_unicos,autorefrescar,mensaje_solo_lectura,opcion_menu) values (
'121',
null,
'M',
'Permisos del Sistema',
'1',
null,
'Permisos',
'Permiso',
'ID_PERMISO',
'PERMISO',
null,
'permiso',
'ASC',
'inv_db.seg_permisos_v',
null,
null,
null,
null,
'4243',
null,
null,
null,
'N',
'N',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A',
null,
null,
null,
null,
null,
'Permisos del Sistema')
;
insert into inv_db.man_paginas_t (id_pagina,id_maestro,tipo,titulo,secuencia,documentacion,plural,singular,campo_id,campo_descripcion,condicion_solo_lectura,ordenar_por,ordenar_dir,consultar,agregar,modificar,borrar,javascript,id_permiso_consultar,id_permiso_agregar,id_permiso_modificar,id_permiso_borrar,imprimir,descargar,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro,pendientes_sql,pendientes_titulo,campos_unicos,autorefrescar,mensaje_solo_lectura,opcion_menu) values (
'129',
null,
'M',
'Parámetros',
'1',
null,
'Parámetros',
'Parámetro',
'id_parametro',
'parametro',
null,
'parametro',
'ASC',
'inv_db.man_parametros_v',
null,
'inv_db.man_parametros_pkg.modificar',
null,
null,
'245',
null,
'247',
null,
'N',
'N',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A',
null,
null,
'parametro',
null,
null,
'Parámetros')
;
alter table inv_db.man_paginas_t modify id_pagina generated by default on null as identity (start with limit value)
;
