insert into inv_db.man_det_acciones_paginas_t (id_accion,id_pagina,secuencia,accion,icono,id_permiso,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro,requiere_seleccion,sentencia,confirmacion_singular,confirmacion_plural) values (
'23',
'110',
'1',
'Revocar permisos',
null,
'3977',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A',
'S',
'inv_db.seg_roles_pkg.revocar_permisos',
'¿Seguro que desea Revocar permisos al registro seleccionado?',
'¿Seguro que desea Revocar permisos a los registros seleccionados?')
;
insert into inv_db.man_det_acciones_paginas_t (id_accion,id_pagina,secuencia,accion,icono,id_permiso,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro,requiere_seleccion,sentencia,confirmacion_singular,confirmacion_plural) values (
'24',
'110',
'2',
'Revocar usuarios',
null,
'3976',
'OPERACIONES',
'06-AUG-24',
null,
null,
'I',
'S',
'inv_db.seg_roles_pkg.remover_usuarios',
'¿Seguro que desea Revocar usuarios al registro seleccionado?',
'¿Seguro que desea Revocar usuarios a los registros seleccionados?')
;
insert into inv_db.man_det_acciones_paginas_t (id_accion,id_pagina,secuencia,accion,icono,id_permiso,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro,requiere_seleccion,sentencia,confirmacion_singular,confirmacion_plural) values (
'55',
'115',
'1',
'Revocar Permisos',
'person_remove',
'4025',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A',
'S',
'inv_db.seg_usuarios_pkg.revocar_acceso',
'¿Seguro que desea Revocar acceso al registro seleccionado?',
'¿Seguro que desea Revocar acceso a los registros seleccionados?')
;
insert into inv_db.man_det_acciones_paginas_t (id_accion,id_pagina,secuencia,accion,icono,id_permiso,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro,requiere_seleccion,sentencia,confirmacion_singular,confirmacion_plural) values (
'61',
'121',
'1',
'Activar',
null,
'4244',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A',
'S',
'inv_db.seg_permisos_pkg.Activar',
'¿Seguro que desea Activar el registro seleccionado?',
'¿Seguro que desea Activar los registros seleccionados?')
;
insert into inv_db.man_det_acciones_paginas_t (id_accion,id_pagina,secuencia,accion,icono,id_permiso,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro,requiere_seleccion,sentencia,confirmacion_singular,confirmacion_plural) values (
'62',
'121',
'2',
'Inactivar',
null,
'4245',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A',
'S',
'inv_db.seg_permisos_pkg.Inactivar',
'¿Seguro que desea Inactivar el registro seleccionado?',
'¿Seguro que desea Inactivar los registros seleccionados?')
;
alter table inv_db.man_det_acciones_paginas_t modify id_accion generated by default on null as identity (start with limit value)
;
