insert into inv_db.seg_secciones_t (id_seccion,seccion,secuencia,icono,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro) values (
'1',
'Movimientos',
'1',
'transactions',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A')
;
insert into inv_db.seg_secciones_t (id_seccion,seccion,secuencia,icono,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro) values (
'2',
'Catálogos',
'2',
'view_list',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A')
;
insert into inv_db.seg_secciones_t (id_seccion,seccion,secuencia,icono,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro) values (
'3',
'Consultas',
'3',
'screen_search_desktop',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A')
;
insert into inv_db.seg_secciones_t (id_seccion,seccion,secuencia,icono,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro) values (
'4',
'Estadísticas',
'4',
'bar_chart',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A')
;
insert into inv_db.seg_secciones_t (id_seccion,seccion,secuencia,icono,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro) values (
'8',
'Configuraciones',
'8',
'settings',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A')
;
insert into inv_db.seg_secciones_t (id_seccion,seccion,secuencia,icono,agregado_por,agregado_en,modificado_por,modificado_en,estado_registro) values (
'9',
'Seguridad del Sistema',
'9',
'policy',
'OPERACIONES',
'06-AUG-24',
null,
null,
'A')
;
alter table inv_db.seg_secciones_t modify id_seccion generated by default on null as identity (start with limit value)
;
