create table inv_db.MAN_TRAZABILIDAD_T
(
  id_trazabilidad NUMBER(10) generated by default on null as identity (start with 882),
  id_pagina       NUMBER(10) not null,
  accion          VARCHAR2(50) not null,
  id_registro     VARCHAR2(100) not null,
  id_usuario      VARCHAR2(100) not null,
  fecha           DATE not null
)

;
comment on table inv_db.MAN_TRAZABILIDAD_T
  is 'Tabla donde se guardan localmente la trazabilidad de cambios si la base de datos de seguridad no está disponible'
;
comment on column inv_db.MAN_TRAZABILIDAD_T.id_trazabilidad
  is 'Id del registro de trazabilidad'
;
comment on column inv_db.MAN_TRAZABILIDAD_T.id_pagina
  is 'Id de la página que generó la trazabilidad'
;
comment on column inv_db.MAN_TRAZABILIDAD_T.accion
  is 'Acción que se realizó sobre el registro'
;
comment on column inv_db.MAN_TRAZABILIDAD_T.id_registro
  is 'Id del registro'
;
comment on column inv_db.MAN_TRAZABILIDAD_T.id_usuario
  is 'Id del usuario que realizó la acción'
;
comment on column inv_db.MAN_TRAZABILIDAD_T.fecha
  is 'Fecha en que se realizó la acción'
;
alter table inv_db.MAN_TRAZABILIDAD_T
  add constraint PK_MAN_TRAZABILIDAD_LOCAL_T_ID primary key (ID_TRAZABILIDAD)
;

