create table inv_db.MAN_DET_ACCIONES_PAGINAS_T
(
  id_accion             NUMBER(10) generated by default on null as identity,
  id_pagina             NUMBER(10) not null,
  secuencia             NUMBER(4) not null,
  accion                VARCHAR2(50) not null,
  icono                 VARCHAR2(25),
  id_permiso            NUMBER(10) not null,
  agregado_por          VARCHAR2(100) not null,
  agregado_en           DATE not null,
  modificado_por        VARCHAR2(100),
  modificado_en         DATE,
  estado_registro               CHAR(1) not null,
  requiere_seleccion    CHAR(1) default 'S' not null,
  sentencia             VARCHAR2(100) not null,
  confirmacion_singular VARCHAR2(500),
  confirmacion_plural   VARCHAR2(500)
)

;
comment on table inv_db.MAN_DET_ACCIONES_PAGINAS_T
  is 'Detalle de acciones que se realizan para uno o más registros de la página actual'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.id_accion
  is 'Id del registro'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.id_pagina
  is 'Id de la página a la que se le agrega esta acción'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.secuencia
  is 'Orden secuencial en que se renderiza el botón de la acción'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.accion
  is 'Título del botón que renderiza la acción'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.icono
  is 'Palabra clave que representa el ícono gráfico a mostrar, ver https://fonts.google.com/icons?icon.style=Rounded'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.id_permiso
  is 'Id del permiso requerido para ejecutar esta acción'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.agregado_por
  is 'Id del usuario que agregó este registro'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.agregado_en
  is 'Fecha en que se agregó el registro'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.modificado_por
  is 'Último usuario que modificó el registro'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.modificado_en
  is 'Última fecha de modificación del registro'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.estado_registro
  is 'Estado del registro, A=Activo,I=Inactivo'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.requiere_seleccion
  is 'S/N que indica si esta acción requiere que se seleccione un registro, no ha sido implementado'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.sentencia
  is 'Método de base de datos a ejecutar'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.confirmacion_singular
  is 'Texto de confirmación cuando se seleccione un solo registro'
;
comment on column inv_db.MAN_DET_ACCIONES_PAGINAS_T.confirmacion_plural
  is 'Texto de confirmación cuando se seleccione más de un registro'
;
alter table inv_db.MAN_DET_ACCIONES_PAGINAS_T
  add constraint PK_DAP primary key (ID_ACCION)
;
alter table inv_db.MAN_DET_ACCIONES_PAGINAS_T
  add constraint UN_DAP_PAGINA_ACCION unique (ID_PAGINA, ACCION)
;
alter table inv_db.MAN_DET_ACCIONES_PAGINAS_T
  add constraint UN_DAP_PAGINA_SECUENCIA unique (ID_PAGINA, SECUENCIA)
;
alter table inv_db.MAN_DET_ACCIONES_PAGINAS_T
  add constraint FK_DAP_PAGINA foreign key (ID_PAGINA)
  references inv_db.MAN_PAGINAS_T (ID_PAGINA)
;
alter table inv_db.MAN_DET_ACCIONES_PAGINAS_T
  add constraint FK_DAP_PERMISO foreign key (ID_PERMISO)
  references inv_db.SEG_PERMISOS_T (ID_PERMISO)
;
alter table inv_db.MAN_DET_ACCIONES_PAGINAS_T
  add constraint CHK_DAp_estado_registro
  check (estado_registro in('A','I'))
;
alter table inv_db.MAN_DET_ACCIONES_PAGINAS_T
  add constraint CHK_DAP_REQUIERE_SELECCION
  check (REQUIERE_SELECCION in('S','N'))
;

