create table inv_db.MAN_PARAMETROS_T
(
  id_parametro    NUMBER(10) generated by default on null as identity,
  parametro       VARCHAR2(50) not null,
  descripcion     VARCHAR2(100) not null,
  valor_actual    VARCHAR2(500),
  agregado_por    VARCHAR2(100) not null,
  agregado_en     DATE not null,
  modificado_por  VARCHAR2(100),
  modificado_en   DATE,
  estado_registro CHAR(1) not null
)

;
comment on table inv_db.MAN_PARAMETROS_T
  is 'Paramétros del sistema'
;
comment on column inv_db.MAN_PARAMETROS_T.id_parametro
  is 'Id del registro'
;
comment on column inv_db.MAN_PARAMETROS_T.parametro
  is 'Código del parámetro (por el cual se busca)'
;
comment on column inv_db.MAN_PARAMETROS_T.descripcion
  is 'Descripción del parámetro'
;
comment on column inv_db.MAN_PARAMETROS_T.valor_actual
  is 'Valor actual'
;
comment on column inv_db.MAN_PARAMETROS_T.agregado_por
  is 'Usuario que agregó el registro'
;
comment on column inv_db.MAN_PARAMETROS_T.agregado_en
  is 'Fecha en que se agregó el registro'
;
comment on column inv_db.MAN_PARAMETROS_T.modificado_por
  is 'Último usuario en modificar el registro'
;
comment on column inv_db.MAN_PARAMETROS_T.modificado_en
  is 'Última fecha de modificación del registro'
;
comment on column inv_db.MAN_PARAMETROS_T.estado_registro
  is 'A=Activo, I=Inactivo'
;
alter table inv_db.MAN_PARAMETROS_T
  add constraint PK_MAN_PARAMETROS_T_ID primary key (ID_PARAMETRO)
;
alter table inv_db.MAN_PARAMETROS_T
  add constraint UN_MAN_PARAMETROS_T_PARAMETRO unique (PARAMETRO)
;
alter table inv_db.MAN_PARAMETROS_T
  add constraint CK_MAN_PARAMETROS_T_ESTADO
  check (estado_registro in ('A','I'))
;

