create table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
(
  id_columna        NUMBER(10) generated by default on null as identity,
  id_pagina         NUMBER(10) not null,
  secuencia         NUMBER(3) not null,
  columna           VARCHAR2(100) not null,
  titulo            VARCHAR2(1000),
  prefijo           VARCHAR2(1000),
  sufijo            VARCHAR2(1000),
  expresion         VARCHAR2(500),
  grupo             VARCHAR2(100),
  tipo_de_dato      VARCHAR2(15) not null,
  longitud          NUMBER(7),
  consultar         CHAR(1) not null,
  estilo_consultar  VARCHAR2(500),
  ver               CHAR(1) not null,
  estilo_ver        VARCHAR2(500),
  condicion_ver     VARCHAR2(1000),
  agregar           CHAR(1) not null,
  estilo_agregar    VARCHAR2(500),
  condicion_agregar VARCHAR2(1000),
  modificar         CHAR(1) not null,
  estilo_modificar  VARCHAR2(500),
  condicion_modificar VARCHAR2(1000),
  imprimir          CHAR(1) not null,
  estilo_imprimir   VARCHAR2(500),
  tipo_total        CHAR(1),
  layout            CHAR(1),
  alineacion        CHAR(1),
  visible_en        CHAR(1),
  requerido         CHAR(1) not null,
  autopostback      CHAR(1) not null,
  regexp_validacion VARCHAR2(500),
  regexp_mensaje    VARCHAR2(100),
  valor_minimo      CLOB,
  valor_maximo      CLOB,
  valor_default     CLOB,
  lista_de_valores  CLOB,
  agregado_por      VARCHAR2(100) not null,
  agregado_en       DATE not null,
  modificado_por    VARCHAR2(100),
  modificado_en     DATE,
  estado_registro           CHAR(1) not null,
  trazabilidad      CHAR(1) default 'S' not null
)

;
comment on table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  is 'Definición de la diferentes columnas que se muestran en una página.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.id_columna
  is 'Primary key autogenerado del registro.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.id_pagina
  is 'FK a man_paginas_t, indica a que página pertenece esta columna.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.secuencia
  is 'Orden en que se muestran las columnas.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.columna
  is 'Nombre de la columna de la vista o sql de donde proviene la data (el DataField).'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.titulo
  is 'Título que se muestra para dicha columna (puede tener acentos, abreviaturas, etc).'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.prefijo
  is 'Título adicional que se renderiza antes   del control para dicha columna (ej. campo EDAD, título "18-65").'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.sufijo
  is 'Título adicional que se renderiza después del control para dicha columna (ej. campo EDAD, título "años").'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.expresion
  is 'Expresión SQL que se renderiza (si se especifica) en vez de la columna (el DataText).'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.grupo
  is 'Para ver,agregar y modificar: sección colapsable que agrupa varios campos afines del formulario.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.tipo_de_dato
  is 'Control que se renderiza en caso de editar/agregar: LBL=Label, TXT=Textbox,HTML=Visor de html,ICON=Icono visual,PASS=Password, NUM=Num. entero, DEC=Num. decimal,FEC=Fecha,HORA=Hora,RAD=Radiobutton,CHK=Checkbox,LOV=Select,DAL=Datalist,MEMO=Textarea,MCHK=Multi-checkboxes,MULTI=Multi-select,IMG=Imagen,DOC=Documento,OL=Lista numerada,UL=Lista buleteada.,HTML,CODE, DOWN=Boton descargador de archivos,FIRMA'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.longitud
  is 'Cantidad máxima de bites que debe aceptar, ej, para el campo período es 6 (maxlength="6").'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.consultar
  is 'S/N que indica si se muestra en el grid de consulta.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.estilo_consultar
  is 'Estilo con que se muestra en el grid de consulta.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.ver
  is 'Indica donde de ve esta columna: S=Siempre,A=al Agregar,M=al Modificar,N=Nunca'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.estilo_ver
  is 'Estilo con que se muestra al ver el registro.'
;
comment on column inv_db.man_det_columnas_paginas_t.condicion_ver 
  is 'Expresión SQL que devuelve S o N para indicar si este campo debe renderizarse o no al ver un registro.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.agregar
  is 'S/N que indica si se muestra al agregar un registro.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.estilo_agregar
  is 'Estilo con que se muestra al agregar el registro.'
;
comment on column inv_db.man_det_columnas_paginas_t.condicion_agregar 
  is 'Expresión SQL que devuelve S o N para indicar si este campo debe renderizarse o no al agregar un registro.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.modificar
  is 'S/N que indica si se muestra al modificar un registro.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.estilo_modificar
  is 'Estilo con que se muestra al modificar el registro.'
;
comment on column inv_db.man_det_columnas_paginas_t.condicion_modificar 
  is 'Expresión SQL que devuelve S o N para indicar si este campo debe renderizarse o no al modificar un registro.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.imprimir
  is 'S/N que indica si se muestra al imprimir un registro.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.estilo_imprimir
  is 'Estilo con que se muestra al imprimir el registro.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.tipo_total
  is 'Tipo de total: Conteo,Suma o Promedio.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.layout
  is 'Para cambiar el layout por default (una columna por fila) y que puedan salir varios columnas en una misma fila: L(left) abre la fila, C(center) se renderizan después de las "layout=L", R(right) cierra la fila.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.alineacion
  is 'Para fines de el grid de consulta: L=Left, C=Center, R=Right.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.visible_en
  is 'Para fines de hacer responsive el Grid, tamaño de pantalla a partir de cual esta columna es visible: S=Small(Phones), M=Medium(tablets),L=Large(momitor), Recomendado: la primera y 1 ó 2 más siempre serán Small,además que haya 2 ó 3 cols M y el resto L.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.requerido
  is 'S/N que indica si es obligatorio llenar el campo.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.autopostback
  is 'S/N que indica si al cambiar algo en el campo se hace post-back (esto es necesario para que controles en cascada estén al tanto del cambio).'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.regexp_validacion
  is 'RegExp que validará la estructura del contenido del campo: ejemplo: un teléfono? ^[2-9]\d{2}-\d{3}-\d{4}$ .'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.regexp_mensaje
  is 'Mensaje de error que se devuelve si se violan las reglas del RegExp.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.valor_minimo
  is 'Valor mínimo aceptable, puede ser una constante fecha, número o letra, acepta una sentencia SQL que devuelve un único valor.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.valor_maximo
  is 'Valor máximo aceptable, puede ser una constante fecha, número o letra, acepta una sentencia SQL que devuelve un único valor.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.valor_default
  is 'Valor que se propone por default al agregar un registro, puede ser una constante fecha, número o letra, acepta "hoy" si la columna es tipo "FEC", o una sentencia SQL que devuelve un único valor.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.lista_de_valores
  is 'Lista de constantes en formato A=Activo,B=Baja,I=Inactivo o una sentencia SQL que devuelve dos columnas, la primera se usará como id y la segunda como descripción para llenar una listade valores.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.agregado_por
  is 'ID del usuario que agregó el registro.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.agregado_en
  is 'Fecha y Hora en que se agregó el registro.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.modificado_por
  is 'ID del último usuario que modificó el registro.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.modificado_en
  is 'Fecha y Hora de la última actualización del registro.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.estado_registro
  is 'Estado del registro: A=Activo, I=Inactivo.'
;
comment on column inv_db.MAN_DET_COLUMNAS_PAGINAS_T.trazabilidad
  is 'S/N que indica si se guarda trazabilidad al manipular los valores de esta columna.'
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint PK_DCP primary key (ID_COLUMNA)
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint UN_DCP_PAGINA_SECUENCIA unique (ID_PAGINA, SECUENCIA)
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint FK_DCP_ID_PAGINA foreign key (ID_PAGINA)
  references inv_db.MAN_PAGINAS_T (ID_PAGINA)
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_DCP_AGREGAR
  check (agregar      in('S','N'))
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_DCP_ALINEACION
  check (alineacion   in('L','C','R'))
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_DCP_AUTOPOSTBACK
  check (autopostback in('S','N'))
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_DCP_CONSULTAR
  check (consultar    in('S','N'))
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_DCp_estado_registro
  check (estado_registro      in('A','I'))
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_DCP_IMPRIMIR
  check (imprimir     in('S','N'))
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_DCP_LAYOUT
  check (layout       in('L','C','R'))
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_DCP_MODIFICAR
  check (modificar    in('S','N'))
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_DCP_REQUERIDO
  check (requerido    in('S','N'))
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_DCP_TIPO_DE_DATO
  check (tipo_de_dato in('LBL','TXT','HTML','CODE','ICON','PASS','NUM','DEC','FLOAT','FEC','HORA','RAD','CHK','LOV','DAL','MEMO','MCHK','MULTI','IMG','DOC','OL','UL','DOWN','FIRMA'))
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_DCP_TIPO_TOTAL
  check (tipo_total in ('C','S','P'))
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_DCP_UPPER_COLUMNA
  check (columna=upper(columna))
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_DCP_VER
  check (ver          in('S','V','A','M','N'))
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_DCP_VISIBLE_EN
  check (visible_en   in('S','M','L'))
;
alter table inv_db.MAN_DET_COLUMNAS_PAGINAS_T
  add constraint CHK_MAN_DET_COLUMNAS_PAGINAS_T_TRAZABILIDAD
  check (trazabilidad in('S','N'))
;

