create table inv_db.MAN_EXCEPCIONES_T
(
  id_excepcion NUMBER(10) generated by default on null as identity (start with 38),
  excepcion    CLOB not null,
  agregado_por VARCHAR2(100) not null,
  agregado_en  DATE not null
)

;
comment on table inv_db.MAN_EXCEPCIONES_T
  is 'Log de excepciones'
;
comment on column inv_db.MAN_EXCEPCIONES_T.id_excepcion
  is 'Id del registro'
;
comment on column inv_db.MAN_EXCEPCIONES_T.excepcion
  is 'Sentencia ejecutada y error de base de datos'
;
comment on column inv_db.MAN_EXCEPCIONES_T.agregado_por
  is 'Usuario que agregó el registro'
;
comment on column inv_db.MAN_EXCEPCIONES_T.agregado_en
  is 'Fecha en que se agregó el registro'
;
alter table inv_db.MAN_EXCEPCIONES_T
  add constraint PK_MAN_EXCEPCIONES_T_ID primary key (ID_EXCEPCION)
;

