create table inv_db.MAN_DET_BANDAS_REPORTES_T
(
  id_banda        NUMBER(10) generated by default on null as identity,
  id_reporte      NUMBER(10) not null,
  secuencia       NUMBER(3) not null,
  banda           VARCHAR2(15) not null,
  detalle_de      VARCHAR2(15),
  consulta        CLOB,
  html            CLOB,
  agregado_por    VARCHAR2(100) not null,
  agregado_en     DATE not null,
  modificado_por  VARCHAR2(100),
  modificado_en   DATE,
  estado_registro CHAR(1) not null
)

;
comment on table inv_db.MAN_DET_BANDAS_REPORTES_T
  is 'Detalle de bandas o secciones (ej: título,encabezado,gran-total,pie de página, etc.) de un reporte personalizado'
;
comment on column inv_db.MAN_DET_BANDAS_REPORTES_T.id_banda
  is 'Id del registro'
;
comment on column inv_db.MAN_DET_BANDAS_REPORTES_T.id_reporte
  is 'Id del reporte al que pertenece'
;
comment on column inv_db.MAN_DET_BANDAS_REPORTES_T.secuencia
  is 'Orden secuencial en que se renderizan las bandas, ej: primero título, segundo encabezados, etc.'
;
comment on column inv_db.MAN_DET_BANDAS_REPORTES_T.banda
  is 'Descripción corta de la banda, ej: encabezado, título, sumario'
;
comment on column inv_db.MAN_DET_BANDAS_REPORTES_T.detalle_de
  is 'Id de la banda de la que es un detalle, ej. un reporte agrupado por departamentos'
;
comment on column inv_db.MAN_DET_BANDAS_REPORTES_T.consulta
  is 'Sentencia que trae la data que se muestra en esta banda'
;
comment on column inv_db.MAN_DET_BANDAS_REPORTES_T.html
  is 'Plantilla HTML que indica como renderizar esta banda'
;
comment on column inv_db.MAN_DET_BANDAS_REPORTES_T.agregado_por
  is 'Id del usuario que agregó el registro'
;
comment on column inv_db.MAN_DET_BANDAS_REPORTES_T.agregado_en
  is 'Fecha en que se agregó el registro'
;
comment on column inv_db.MAN_DET_BANDAS_REPORTES_T.modificado_por
  is 'Último usuario que modificó el registro'
;
comment on column inv_db.MAN_DET_BANDAS_REPORTES_T.modificado_en
  is 'Última fecha en que se modificó el registro'
;
comment on column inv_db.MAN_DET_BANDAS_REPORTES_T.estado_registro
  is 'Estado del registro, A=Activo, I=Inactivo'
;
alter table inv_db.MAN_DET_BANDAS_REPORTES_T
  add constraint PK_MAN_DET_BANDAS_REPORTES_T_ID primary key (ID_BANDA)
;
alter table inv_db.MAN_DET_BANDAS_REPORTES_T
  add constraint PK_MAN_DET_BANDAS_REPORTES_T_BANDA unique (ID_REPORTE, BANDA)
;
alter table inv_db.MAN_DET_BANDAS_REPORTES_T
  add constraint PK_MAN_DET_BANDAS_REPORTES_T_SECUENCIA unique (ID_REPORTE, SECUENCIA)
;
alter table inv_db.MAN_DET_BANDAS_REPORTES_T
  add constraint FK_MAN_DET_BANDAS_REPORTES_T_REPORTE foreign key (ID_REPORTE)
  references inv_db.MAN_REPORTES_T (ID_REPORTE)
;
alter table inv_db.MAN_DET_BANDAS_REPORTES_T
  add constraint CK_MAN_DET_BANDAS_REPORTES_T_ESTADO
  check (estado_registro in ('A','I'))
;

