create table inv_db.MAN_DET_FILTROS_PAGINAS_T
(
  id_filtro         NUMBER(10) generated by default on null as identity,
  id_pagina         NUMBER(10) not null,
  columna           VARCHAR2(100) not null,
  secuencia         NUMBER(4) not null,
  titulo            VARCHAR2(25) not null,
  condicion         VARCHAR2(10) not null,
  requerido			varchar2(1) default 'N' not null,
  tipo_de_dato      VARCHAR2(4) not null,
  autopostback      CHAR(1) not null,
  regexp_validacion VARCHAR2(500),
  regexp_mensaje    VARCHAR2(500),
  longitud          NUMBER(4),
  valor_minimo      VARCHAR2(100),
  valor_maximo      VARCHAR2(100),
  valor_default     VARCHAR2(100),
  lista_de_valores  CLOB,
  estilo            VARCHAR2(100),
  agregado_por      VARCHAR2(100) not null,
  agregado_en       DATE not null,
  modificado_por    VARCHAR2(100),
  modificado_en     DATE,
  estado_registro           CHAR(1) not null
)

;
comment on table inv_db.MAN_DET_FILTROS_PAGINAS_T
  is 'Detalle de las caracteristicas de los filtros que se aplican a una página.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.id_filtro
  is 'Primary key autogenerado del registro.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.id_pagina
  is 'FK a man_paginas_t indicando que página implementa este filtro.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.columna
  is 'columna que se filtrará.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.secuencia
  is 'Orden en que se renderizarán los diferentes filtros de una página.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.titulo
  is 'Label que se renderizará a la izquierda del control del filtro.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.condicion
  is 'Condición lógica con que se evaluará el campo versus el valor especificado por el usuario (igualdad, mayor que, menor que, etc)'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.requerido
  is 'Indica si este filtro es: S=Requerido,T=Tentativo (debe especificar al menos uno),N=Opcional'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.tipo_de_dato
  is 'Control que se renderiza en caso de editar/agregar:LBL=Label, TXT=Textbox,NUM=Num. entero, DEC=Num. decimal,FEC=Fecha,HORA=Hora,RAD=Radiobutton,CHK=Checkbox,LOV=Select,DAL=Datalist'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.autopostback
  is 'S/N que indica si al cambiar algo en el campo se hace post-back (esto es necesario para que controles en cascada estén al tanto del cambio).'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.regexp_validacion
  is 'RegExp que validará la estructura del contenido del campo: ej: un teléfono? ^[2-9]\d{2}-\d{3}-\d{4}$ .'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.regexp_mensaje
  is 'Mensaje de error que se devuelve si se violan las reglas del RegExp.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.longitud
  is 'Cantidad máxima de bites que debe aceptar, ej, para el campo período es 6 (maxlength="6").'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.valor_minimo
  is 'Valor mínimo aceptable, puede ser una constante fecha, número o letra, acepta una sentencia SQL que devuelve un único valor.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.valor_maximo
  is 'Valor máximo aceptable, puede ser una constante fecha, número o letra, acepta una sentencia SQL que devuelve un único valor.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.valor_default
  is 'Valor que se propone por default al agregar un registro, puede ser una constante fecha, número o letra, acepta "hoy" si la columna es tipo "FEC", o una sentencia SQL que devuelve un único valor.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.lista_de_valores
  is 'Lista de constantes en formato A=Activo,B=Baja,I=Inactivo o una sentencia SQL que devuelve dos columnas, la primera se usará como id y la segunda como descripción para una lista de valores.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.estilo
  is 'Estilo particular para el control que se renderizará (opcional).'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.agregado_por
  is 'ID del usuario que agregó el registro.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.agregado_en
  is 'Fecha y Hora en que se agregó el registro.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.modificado_por
  is 'ID del último usuario que modificó el registro.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.modificado_en
  is 'Fecha y Hora de la última actualización del registro.'
;
comment on column inv_db.MAN_DET_FILTROS_PAGINAS_T.estado_registro
  is 'Estado del registro: A=Activo, I=Inactivo.'
;
alter table inv_db.MAN_DET_FILTROS_PAGINAS_T
  add constraint PK_DFP primary key (ID_FILTRO)
;
alter table inv_db.MAN_DET_FILTROS_PAGINAS_T
  add constraint UN_DFP_PAGINA_SEUENCIA unique (ID_PAGINA, SECUENCIA)
;
alter table inv_db.MAN_DET_FILTROS_PAGINAS_T
  add constraint UN_DFP_PAGINA_TITULO unique (ID_PAGINA, TITULO)
;
alter table inv_db.MAN_DET_FILTROS_PAGINAS_T
  add constraint FK_DFP_PAGINA foreign key (ID_PAGINA)
  references inv_db.MAN_PAGINAS_T (ID_PAGINA)
;
alter table inv_db.MAN_DET_FILTROS_PAGINAS_T
  add constraint CHK_DFP_AUTOPOSTBACK
  check (autopostback in('S','N'))
;
alter table inv_db.MAN_DET_FILTROS_PAGINAS_T
  add constraint CHK_DFP_CONDICION
  check (condicion in ('=','>','>=','<','<=','<>','LIKE','LIKE_U','IN'))
;
alter table inv_db.MAN_DET_FILTROS_PAGINAS_T
  add constraint CHK_DFp_estado_registro
  check (estado_registro  in('A','I'))
;
alter table inv_db.MAN_DET_FILTROS_PAGINAS_T
  add constraint CHK_DFP_REQUERIDO
  check (requerido  in('S','T','N'))
;
alter table inv_db.MAN_DET_FILTROS_PAGINAS_T
  add constraint CHK_DFP_TIPO_DE_DATO
  check (tipo_de_dato in('LBL','TXT','NUM','DEC','FEC','HORA','RAD','CHK','LOV','DAL'))
;

