create table inv_db.MAN_MENSAJES_T
(
  id_mensaje     NUMBER(10) generated by default on null as identity,
  objeto         VARCHAR2(100) not null,
  codigo         VARCHAR2(15) not null,
  mensaje        VARCHAR2(200) not null,
  agregado_por   VARCHAR2(100) not null,
  agregado_en    DATE not null,
  modificado_por VARCHAR2(100),
  modificado_en  DATE,
  estado_registro        CHAR(1) not null
)

;
comment on table inv_db.MAN_MENSAJES_T
  is 'Catálogo de mensajes de error que devuelve cada método de base de datos'
;
comment on column inv_db.MAN_MENSAJES_T.id_mensaje
  is 'Id del registro'
;
comment on column inv_db.MAN_MENSAJES_T.objeto
  is 'Nombre del objeto de base de datos'
;
comment on column inv_db.MAN_MENSAJES_T.codigo
  is 'Código del mensaje'
;
comment on column inv_db.MAN_MENSAJES_T.mensaje
  is 'Texto del mensaje'
;
comment on column inv_db.MAN_MENSAJES_T.agregado_por
  is 'Usuario que agregó el registro'
;
comment on column inv_db.MAN_MENSAJES_T.agregado_en
  is 'Fecha en que se agregó el registro'
;
comment on column inv_db.MAN_MENSAJES_T.modificado_por
  is 'Último usuario en modificar el registro'
;
comment on column inv_db.MAN_MENSAJES_T.modificado_en
  is 'Última fecha de modificación del registro'
;
comment on column inv_db.MAN_MENSAJES_T.estado_registro
  is 'Estado actual del registro'
;
alter table inv_db.MAN_MENSAJES_T
  add constraint PK_MAN_MENSAJES_T_ID primary key (ID_MENSAJE)
;
alter table inv_db.MAN_MENSAJES_T
  add constraint UN_MAN_MENSAJES_T_OBJ_COD unique (OBJETO, CODIGO)
;
alter table inv_db.MAN_MENSAJES_T
  add constraint CK_MAN_MENSAJE_T_ESTATUS
  check (estado_registro in('A','I'))
;

