create table inv_db.MAN_PAGINAS_T
(
  id_pagina              NUMBER(10) generated by default on null as identity,
  id_maestro             NUMBER(10),
  tipo                   CHAR(1) not null,
  titulo                 VARCHAR2(100) not null,
  icono					 varchar2(20),
  secuencia              NUMBER(3),
  documentacion          CLOB,
  plural                 VARCHAR2(100) not null,
  singular               VARCHAR2(100) not null,
  campo_id               VARCHAR2(100) not null,
  campo_descripcion      VARCHAR2(100) not null,
  condicion_solo_lectura VARCHAR2(500),
  ordenar_por            VARCHAR2(100),
  ordenar_dir            VARCHAR2(4),
  consultar              VARCHAR2(2000) not null,
  agregar                VARCHAR2(200),
  modificar              VARCHAR2(200),
  borrar                 VARCHAR2(200),
  javascript             CLOB,
  id_permiso_consultar   NUMBER(10),
  id_permiso_agregar     NUMBER(10),
  id_permiso_modificar   NUMBER(10),
  id_permiso_borrar      NUMBER(10),
  imprimir               CHAR(1) not null,
  descargar              CHAR(1) not null,
  agregado_por           VARCHAR2(100) not null,
  agregado_en            DATE not null,
  modificado_por         VARCHAR2(100),
  modificado_en          DATE,
  estado_registro                CHAR(1) not null,
  pendientes_sql         CLOB,
  pendientes_titulo      VARCHAR2(100),
  campos_unicos          VARCHAR2(1000),
  autorefrescar          NUMBER(3),
  mensaje_solo_lectura   VARCHAR2(500),
  opcion_menu            VARCHAR2(100)
)

;
comment on table inv_db.MAN_PAGINAS_T
  is 'Tabla donde se guarda un registro configurable por el desarrollador, por cada mantenimiento o consulta.'
;
comment on column inv_db.MAN_PAGINAS_T.id_pagina
  is 'Id de la página, autogenerado'
;
comment on column inv_db.MAN_PAGINAS_T.id_maestro
  is 'Foreign key a la misma tabla de páginas indicando de cual registro es su página maestra'
;
comment on column inv_db.MAN_PAGINAS_T.tipo
  is 'Tipo de página: M=Mantenimiento CRUD, A=Solo agregar (como "deje sus comentarios"), E=Solo editar (como "perfil usuario"), B=Gráfico de barras, L=Gráfico de Líneas, P=Gráfico de Pastel'
;
comment on column inv_db.MAN_PAGINAS_T.titulo
  is 'Texto que se presentará como el título de la página, no se implementa en los detalles (lo infiere de su maestro).'
;
comment on column inv_db.MAN_PAGINAS_T.icono
  is 'Representación gráfica de esta página en el menú'
;
comment on column inv_db.MAN_PAGINAS_T.secuencia
  is 'Orden en que se muestran los tabs que representan los detalles de una página'
;
comment on column inv_db.MAN_PAGINAS_T.documentacion
  is 'Texto HTML que sirve de documento de ayuda para esta página.'
;
comment on column inv_db.MAN_PAGINAS_T.plural
  is 'Como referirse a los registros de esta página en plural'
;
comment on column inv_db.MAN_PAGINAS_T.singular
  is 'Como referirse a un registro de esta página en singular'
;
comment on column inv_db.MAN_PAGINAS_T.campo_id
  is 'Nombre del campo que por sí solo es único (ej: para sre_empleadores_t es id_registro_patronal)'
;
comment on column inv_db.MAN_PAGINAS_T.campo_descripcion
  is 'Nombre del campo que describe un registro de esta página (ej: para sre_empleadores_t es razon_social).'
;
comment on column inv_db.MAN_PAGINAS_T.condicion_solo_lectura
  is 'Condición SQL que devuelve S o N e indica si este registro debe ser de solo lectura (ej: en sfc_facturas_t es case status when "PA" then "S" else "N" end)'
;
comment on column inv_db.MAN_PAGINAS_T.ordenar_por
  is 'Para el grid de consulta: por qué campo vendrá ordenado por default'
;
comment on column inv_db.MAN_PAGINAS_T.ordenar_dir
  is 'Para el grid de consulta: en qué dirección vendrá ordenado por default (ASC o DESC)'
;
comment on column inv_db.MAN_PAGINAS_T.consultar
  is 'Para el grid de consulta: nombre de la vista o sentencia sql de donde saldrá la data.'
;
comment on column inv_db.MAN_PAGINAS_T.agregar
  is 'El método de base de datos que valída y agrega un registro'
;
comment on column inv_db.MAN_PAGINAS_T.modificar
  is 'El método de base de datos que valída y modifica un registro'
;
comment on column inv_db.MAN_PAGINAS_T.borrar
  is 'El método de base de datos que valida y borra un registro'
;
comment on column inv_db.MAN_PAGINAS_T.javascript
  is 'Código javascript para interactuar con cualquier elemento de la página'
;
comment on column inv_db.MAN_PAGINAS_T.id_permiso_consultar
  is 'FK a inv_db.seg_permisos_t, ID del permiso que permite entrar a esta página, obligatorio'
;
comment on column inv_db.MAN_PAGINAS_T.id_permiso_agregar
  is 'FK a inv_db.seg_permisos_t, ID del permiso que permite agregar registros, opcional'
;
comment on column inv_db.MAN_PAGINAS_T.id_permiso_modificar
  is 'FK a inv_db.seg_permisos_t, ID del permiso que permite modificar registros, opcional'
;
comment on column inv_db.MAN_PAGINAS_T.id_permiso_borrar
  is 'FK a inv_db.seg_permisos_t, ID del permiso que permite borrar registros, opcional'
;
comment on column inv_db.MAN_PAGINAS_T.imprimir
  is 'S/N que indica si se muestra el botón de imprimir en papel los registros que se muestran en pantalla'
;
comment on column inv_db.MAN_PAGINAS_T.descargar
  is 'S/N que indica si se muestra el botón de exportar a excel los registros que se muestran en pantalla'
;
comment on column inv_db.MAN_PAGINAS_T.agregado_por
  is 'ID del usuario que agregó el registro'
;
comment on column inv_db.MAN_PAGINAS_T.agregado_en
  is 'Fecha y Hora en que se agregó el registro'
;
comment on column inv_db.MAN_PAGINAS_T.modificado_por
  is 'ID del último usuario que modificó el registro'
;
comment on column inv_db.MAN_PAGINAS_T.modificado_en
  is 'Fecha y Hora de la última actualización del registro'
;
comment on column inv_db.MAN_PAGINAS_T.estado_registro
  is 'Estado del registro: A=Activo, I=Inactivo'
;
comment on column inv_db.MAN_PAGINAS_T.pendientes_sql
  is 'Vista o SQL que determina los registros de esta página que estan pendientes de realizarles alguna tarea'
;
comment on column inv_db.MAN_PAGINAS_T.pendientes_titulo
  is 'Título que reciben los registros pendientes que devuelva la consulta en en campo PENDIENTES_SQL'
;
comment on column inv_db.MAN_PAGINAS_T.campos_unicos
  is 'Campo o combinación de campos que deben ser únicos, en formato: campo1-campo2,campo3, ej: en sre_ciudadanos_t es id_nss,tipo_documento-no_documento'
;
comment on column inv_db.MAN_PAGINAS_T.autorefrescar
  is 'Cantidad de segundos por mínimos a los que se auto-refresca la página, null significa que no se auto-refresca'
;
comment on column inv_db.MAN_PAGINAS_T.mensaje_solo_lectura
  is 'Mensaje al usuario que explica la condición de solo lectura.'
;
comment on column inv_db.MAN_PAGINAS_T.opcion_menu
  is 'Nombre de la opción del menú para esta página'
;
alter table inv_db.MAN_PAGINAS_T
  add constraint PK_PAG primary key (ID_PAGINA)
;
alter table inv_db.MAN_PAGINAS_T
  add constraint UN_PAG_TITULO unique (TITULO)
;
alter table inv_db.MAN_PAGINAS_T
  add constraint FK_PAG_AGREGAR foreign key (ID_PERMISO_AGREGAR)
  references inv_db.SEG_PERMISOS_T (ID_PERMISO)
;
alter table inv_db.MAN_PAGINAS_T
  add constraint FK_PAG_BORRAR foreign key (ID_PERMISO_BORRAR)
  references inv_db.SEG_PERMISOS_T (ID_PERMISO)
;
alter table inv_db.MAN_PAGINAS_T
  add constraint FK_PAG_CONSULTAR foreign key (ID_PERMISO_CONSULTAR)
  references inv_db.SEG_PERMISOS_T (ID_PERMISO)
;
alter table inv_db.MAN_PAGINAS_T
  add constraint FK_PAG_MODIFICAR foreign key (ID_PERMISO_MODIFICAR)
  references inv_db.SEG_PERMISOS_T (ID_PERMISO)
;
alter table inv_db.MAN_PAGINAS_T
  add constraint CHK_DESCARGAR
  check (descargar in('S','N'))
;
alter table inv_db.MAN_PAGINAS_T
  add constraint CHK_IMPRIMIR
  check (imprimir in('S','N'))
;
alter table inv_db.MAN_PAGINAS_T
  add constraint CHK_PAG_ESTATUS
  check (estado_registro in('A','I'))
;
alter table inv_db.MAN_PAGINAS_T
  add constraint CHK_PAG_TIPO
  check (tipo in('M','A','E','P','B','L'))
;

alter table inv_db.man_paginas_t
  add cerrar_al_guardar char(1) default 'N' not null
  ;
alter table inv_db.man_paginas_t 
  add constraint chk_man_paginas_t_cerrar 
  check (cerrar_al_guardar in('S','N'))
  ;
comment on column inv_db.man_paginas_t.cerrar_al_guardar 
  is 'S/N que indica si se debe cerrar la página al guardar'
;
