create table inv_db.MAN_DET_TRAZABILIDAD_T
(
  id_det_trazabilidad NUMBER(10) generated by default on null as identity (start with 6727),
  id_trazabilidad     NUMBER(10) not null,
  columna             VARCHAR2(100) not null,
  antes               CLOB,
  despues             CLOB
)

;
comment on table inv_db.MAN_DET_TRAZABILIDAD_T
  is 'Tabla donde se guardan localmente los detalles de trazabilidad si la base de datos de seguridad no está disponible'
;
comment on column inv_db.MAN_DET_TRAZABILIDAD_T.id_det_trazabilidad
  is 'Id del detalle de trazabilidad'
;
comment on column inv_db.MAN_DET_TRAZABILIDAD_T.id_trazabilidad
  is 'Id de la trazabilidad'
;
comment on column inv_db.MAN_DET_TRAZABILIDAD_T.columna
  is 'Columna del registro de la tabla'
;
comment on column inv_db.MAN_DET_TRAZABILIDAD_T.antes
  is 'Valor de la columna antes de la acción'
;
comment on column inv_db.MAN_DET_TRAZABILIDAD_T.despues
  is 'Valor de la columna después de la acción'
;
alter table inv_db.MAN_DET_TRAZABILIDAD_T
  add constraint PK_MAN_DET_TRAZABILIDAD_LOCAL_T_ID primary key (ID_DET_TRAZABILIDAD)
;
alter table inv_db.MAN_DET_TRAZABILIDAD_T
  add constraint FK_MAN_DET_TRAZABILIDAD_LOCAL_T_ID_TRAZABILIDAD foreign key (ID_TRAZABILIDAD)
  references inv_db.MAN_TRAZABILIDAD_T (ID_TRAZABILIDAD)
;

