create table inv_db.MAN_REPORTES_T
(
  id_reporte         NUMBER(10) generated by default on null as identity,
  id_pagina          NUMBER(10) not null,
  reporte            VARCHAR2(50) not null,
  alto               VARCHAR2(15),
  ancho              VARCHAR2(15),
  orientacion        VARCHAR2(15),
  agregado_por       VARCHAR2(100) not null,
  agregado_en        DATE not null,
  modificado_por     VARCHAR2(100),
  modificado_en      DATE,
  estado_registro    CHAR(1) not null,
  secuencia          NUMBER(1) default 1 not null,
  sentencia          VARCHAR2(500),
  estilos            CLOB,
  seleccion_multiple CHAR(1) default 'S' not null
)

;
comment on table inv_db.MAN_REPORTES_T
  is 'Reportes personalidados de cada página'
;
comment on column inv_db.MAN_REPORTES_T.id_reporte
  is 'Id del reporte'
;
comment on column inv_db.MAN_REPORTES_T.id_pagina
  is 'Id de la página a la que pertenece'
;
comment on column inv_db.MAN_REPORTES_T.reporte
  is 'Nombre del reporte, se renderiza como el botón de impresión'
;
comment on column inv_db.MAN_REPORTES_T.alto
  is 'Altura del papel en pulgadas'
;
comment on column inv_db.MAN_REPORTES_T.ancho
  is 'Anchura del papel en pulgadas'
;
comment on column inv_db.MAN_REPORTES_T.orientacion
  is 'Orientación, pendiente de implementarse'
;
comment on column inv_db.MAN_REPORTES_T.agregado_por
  is 'Id del usuario que agregó el registro'
;
comment on column inv_db.MAN_REPORTES_T.agregado_en
  is 'Fecha en que se agregó el registro'
;
comment on column inv_db.MAN_REPORTES_T.modificado_por
  is 'Último usuario que modificó el registro'
;
comment on column inv_db.MAN_REPORTES_T.modificado_en
  is 'Última fecha de modificación del registro'
;
comment on column inv_db.MAN_REPORTES_T.estado_registro
  is 'Estado del registro: A=Activo,I=Inactivo'
;
comment on column inv_db.MAN_REPORTES_T.secuencia
  is 'Orden secuencial en que se renderiza el botón de imprimir de este reporte'
;
comment on column inv_db.MAN_REPORTES_T.sentencia
  is 'Stored procedure que se ejecuta después de imprimir este reporte (por si hay que marcar un registro como impreso)'
;
comment on column inv_db.MAN_REPORTES_T.estilos
  is 'Hoja de estilo de este reporte'
;
comment on column inv_db.MAN_REPORTES_T.seleccion_multiple
  is 'S/N que indica si este reporte requiere imprimirse individualmente.'
;
alter table inv_db.MAN_REPORTES_T
  add constraint PK_MAN_REPORTES_T_ID primary key (ID_REPORTE)
;
alter table inv_db.MAN_REPORTES_T
  add constraint PK_MAN_REPORTES_T_REPORTE unique (ID_PAGINA, REPORTE)
;
alter table inv_db.MAN_REPORTES_T
  add constraint FK_MAN_REPORTES_T_PAGINA foreign key (ID_PAGINA)
  references inv_db.MAN_PAGINAS_T (ID_PAGINA)
;
alter table inv_db.MAN_REPORTES_T
  add constraint CK_MAN_REPORTES_T_ESTADO
  check (estado_registro in ('A','I'))
;
alter table inv_db.MAN_REPORTES_T
  add constraint CK_MAN_REPORTES_T_SELECCION
  check (seleccion_multiple in('S','N'))
;

