create table inv_db.SEG_BUZON_MENSAJES_T
(
  id_buzon_mensaje NUMBER(10) generated by default on null as identity,
  id_usuario       VARCHAR2(100) not null,
  asunto           VARCHAR2(150) not null,
  mensaje          CLOB not null,
  enviado_en       DATE not null,
  leido_en         DATE,
  leido            VARCHAR2(1) not null
)

;
comment on table inv_db.SEG_BUZON_MENSAJES_T
  is 'Buzón de mensajes a los usuarios'
;
comment on column inv_db.SEG_BUZON_MENSAJES_T.id_buzon_mensaje
  is 'ID generado por cada registro insertado en la tabla SEG_BUZON_MENSAJES_T'
;
comment on column inv_db.SEG_BUZON_MENSAJES_T.id_usuario
  is 'ID del usuario'
;
comment on column inv_db.SEG_BUZON_MENSAJES_T.asunto
  is 'Asunto del mensaje '
;
comment on column inv_db.SEG_BUZON_MENSAJES_T.mensaje
  is 'Mensaje '
;
comment on column inv_db.SEG_BUZON_MENSAJES_T.enviado_en
  is 'Fecha en que se envió el mensaje'
;
comment on column inv_db.SEG_BUZON_MENSAJES_T.leido_en
  is 'Fecha en que se leyó el mensaje'
;
comment on column inv_db.SEG_BUZON_MENSAJES_T.leido
  is '(Indicador de lectura del mensaje (S=Si,N=No)'
;
alter table inv_db.SEG_BUZON_MENSAJES_T
  add constraint PK_SEG_BUZON_MENSAJES_T primary key (ID_BUZON_MENSAJE)
;
alter table inv_db.SEG_BUZON_MENSAJES_T
  add constraint CK_LEIDO_SEG_BZMSG
  check (LEIDO IN('S','N'))
;

