create table inv_db.SEG_SECCIONES_T
(
  id_seccion     NUMBER(10) generated by default on null as identity (start with 122),
  seccion        VARCHAR2(50) not null,
  secuencia      NUMBER(3),
  icono          VARCHAR2(35),
  agregado_por   VARCHAR2(100) not null,
  agregado_en    DATE not null,
  modificado_por VARCHAR2(100),
  modificado_en  DATE,
  estado_registro        CHAR(1) not null
)

;
comment on table inv_db.SEG_SECCIONES_T
  is 'Catálogo de secciones del menú'
;
comment on column inv_db.SEG_SECCIONES_T.id_seccion
  is 'Id de la sección'
;
comment on column inv_db.SEG_SECCIONES_T.seccion
  is 'Descripción de la sección del menú'
;
comment on column inv_db.SEG_SECCIONES_T.secuencia
  is 'Orden secuencial en que se renderiza'
;
comment on column inv_db.SEG_SECCIONES_T.icono
  is 'Código del ícono gráfico que renderiza la seccion, ver https://fonts.google.com/icons?icon.style=Rounded'
;
comment on column inv_db.SEG_SECCIONES_T.agregado_por
  is 'Id del usuario que agregó el registro'
;
comment on column inv_db.SEG_SECCIONES_T.agregado_en
  is 'Fecha en que se agregó el registro'
;
comment on column inv_db.SEG_SECCIONES_T.modificado_por
  is 'Último usuario que modificó el registro'
;
comment on column inv_db.SEG_SECCIONES_T.modificado_en
  is 'Última fecha de modificación del registro'
;
comment on column inv_db.SEG_SECCIONES_T.estado_registro
  is 'Estado del registro: A=Activo,I=Inactivo'
;
alter table inv_db.SEG_SECCIONES_T
  add constraint PK_SEG_SECCIONES_T_ID primary key (ID_SECCION)
;
alter table inv_db.SEG_SECCIONES_T
  add constraint UN_SEG_SECCIONES_T_SECCION unique (SECCION)
;
alter table inv_db.SEG_SECCIONES_T
  add constraint CK_SEG_SECCIONES_T_ESTATUS
  check (estado_registro in('A','I'))
;

