create table inv_db.SEG_DET_PERMISOS_ROLES_T
(
  id_permiso_rol NUMBER(10) generated by default on null as identity,
  id_rol         NUMBER(10) not null,
  id_permiso     NUMBER(10) not null,
  agregado_por   VARCHAR2(100) not null,
  agregado_en    DATE not null,
  modificado_por VARCHAR2(100),
  modificado_en  DATE,
  estado_registro        CHAR(1) not null
)

;
comment on table inv_db.SEG_DET_PERMISOS_ROLES_T
  is 'Detalle de permisos asignados a un rol'
;
comment on column inv_db.SEG_DET_PERMISOS_ROLES_T.id_permiso_rol
  is 'Id del registro'
;
comment on column inv_db.SEG_DET_PERMISOS_ROLES_T.id_rol
  is 'Id del rol'
;
comment on column inv_db.SEG_DET_PERMISOS_ROLES_T.id_permiso
  is 'Id del permiso asignado a este rol'
;
comment on column inv_db.SEG_DET_PERMISOS_ROLES_T.agregado_por
  is 'Usuario que agregó el registro'
;
comment on column inv_db.SEG_DET_PERMISOS_ROLES_T.agregado_en
  is 'Fecha en que se agregó el registro'
;
comment on column inv_db.SEG_DET_PERMISOS_ROLES_T.modificado_por
  is 'Último usuario en modificar el registro'
;
comment on column inv_db.SEG_DET_PERMISOS_ROLES_T.modificado_en
  is 'última fecha de modificación del registro'
;
comment on column inv_db.SEG_DET_PERMISOS_ROLES_T.estado_registro
  is 'Estado actual del registro'
;
alter table inv_db.SEG_DET_PERMISOS_ROLES_T
  add constraint PK_SEG_DET_PERMISOS_ROLES_T_ID primary key (ID_PERMISO_ROL)
;
alter table inv_db.SEG_DET_PERMISOS_ROLES_T
  add constraint UN_SEG_DET_PERMISOS_ROLES_T_ROL_PER unique (ID_ROL, ID_PERMISO)
;
alter table inv_db.SEG_DET_PERMISOS_ROLES_T
  add constraint FK_SEG_DET_PERMISOS_ROLES_T_PERMISO foreign key (ID_PERMISO)
  references inv_db.SEG_PERMISOS_T (ID_PERMISO)
;
alter table inv_db.SEG_DET_PERMISOS_ROLES_T
  add constraint FK_SEG_DET_PERMISOS_ROLES_T_ROL foreign key (ID_ROL)
  references inv_db.SEG_ROLES_T (ID_ROL)
;
alter table inv_db.SEG_DET_PERMISOS_ROLES_T
  add constraint CHK_SEG_DET_PERMISOS_ROLES_T_ESTATUS
  check (estado_registro in ('A','I'))
;

