create table inv_db.SEG_ROLES_T
(
  id_rol         NUMBER(10) generated by default on null as identity,
  rol            VARCHAR2(50) not null,
  agregado_por   VARCHAR2(100) not null,
  agregado_en    DATE not null,
  modificado_por VARCHAR2(100),
  modificado_en  DATE,
  estado_registro        CHAR(1) not null
)

;
comment on table inv_db.SEG_ROLES_T
  is 'Detalle de roles creados para un sistema específico'
;
comment on column inv_db.SEG_ROLES_T.id_rol
  is 'Id del registro'
;
comment on column inv_db.SEG_ROLES_T.rol
  is 'Nombre del role'
;
comment on column inv_db.SEG_ROLES_T.agregado_por
  is 'Usuario que agregó el registro'
;
comment on column inv_db.SEG_ROLES_T.agregado_en
  is 'Fecha en que se agregó el registro'
;
comment on column inv_db.SEG_ROLES_T.modificado_por
  is 'Último usuario en modificar el registro'
;
comment on column inv_db.SEG_ROLES_T.modificado_en
  is 'Última fecha de modificación del registro'
;
comment on column inv_db.SEG_ROLES_T.estado_registro
  is 'Estado actual del registro'
;
alter table inv_db.SEG_ROLES_T
  add constraint PK_SEG_ROLES_T primary key (ID_ROL)
;
alter table inv_db.SEG_ROLES_T
  add constraint UN_SEG_ROLES_T_ROL unique (ROL)
;
alter table inv_db.SEG_ROLES_T
  add constraint CHK_SEG_ROLES_T_ESTATUS
  check (estado_registro in ('A','I'))
;

