create table inv_db.SEG_DET_ROLES_USUARIOS_T
(
  id_rol_usuario  NUMBER(10) generated by default on null as identity,
  id_usuario      VARCHAR2(100) not null,
  administrador   CHAR(1) not null,
  id_rol          NUMBER(10),
  agregado_por    VARCHAR2(100) not null,
  agregado_en     DATE not null,
  modificado_por  VARCHAR2(100),
  modificado_en   DATE,
  estado_registro CHAR(1) not null
)

;
comment on table inv_db.SEG_DET_ROLES_USUARIOS_T
  is 'Detalle de usuarios que están registrados para poder usar el sistema'
;
comment on column inv_db.SEG_DET_ROLES_USUARIOS_T.id_rol_usuario
  is 'Id del registro'
;
comment on column inv_db.SEG_DET_ROLES_USUARIOS_T.id_usuario
  is 'Id del usuario registrado para usar este sistema'
;
comment on column inv_db.SEG_DET_ROLES_USUARIOS_T.administrador
  is 'Flag que indica si es administrador o no (S/N)'
;
comment on column inv_db.SEG_DET_ROLES_USUARIOS_T.id_rol
  is 'Id de uno de los roles de este sistema asignado a este usuario (solo en caso de no ser administrador)'
;
comment on column inv_db.SEG_DET_ROLES_USUARIOS_T.agregado_por
  is 'Usuario que agregó el registro'
;
comment on column inv_db.SEG_DET_ROLES_USUARIOS_T.agregado_en
  is 'Fecha en que se agregó el registro'
;
comment on column inv_db.SEG_DET_ROLES_USUARIOS_T.modificado_por
  is 'Último usuario en modificar el registro'
;
comment on column inv_db.SEG_DET_ROLES_USUARIOS_T.modificado_en
  is 'Última fecha de modificación del registro'
;
comment on column inv_db.SEG_DET_ROLES_USUARIOS_T.estado_registro
  is 'Estado actual del registro'
;
alter table inv_db.SEG_DET_ROLES_USUARIOS_T
  add constraint PK_SEG_DET_ROLES_USUARIOS_T_ID primary key (ID_ROL_USUARIO)
;
alter table inv_db.SEG_DET_ROLES_USUARIOS_T
  add constraint FK_MR_ROL foreign key (ID_ROL)
  references inv_db.SEG_ROLES_T (ID_ROL)
;
alter table inv_db.SEG_DET_ROLES_USUARIOS_T
  add constraint CHK_DUM_ESTATUS
  check (estado_registro in('A','I'))
;
alter table inv_db.SEG_DET_ROLES_USUARIOS_T
  add constraint CHK_SEG_DET_ROLES_USUARIOS_T_TIPO_ROL
  check ((ADMINISTRADOR='S' and id_rol is null) or (ADMINISTRADOR='N' and id_rol is not null))
;

