create table inv_db.SEG_PERMISOS_T
(
  id_permiso            NUMBER(10) generated by default on null as identity,
  permiso               VARCHAR2(100) not null,
  direccion_electronica VARCHAR2(500),
  icono                 VARCHAR2(35),
  secuencia             NUMBER(3),
  id_seccion            NUMBER(10),
  agregado_por          VARCHAR2(100) not null,
  agregado_en           DATE not null,
  modificado_por        VARCHAR2(100),
  modificado_en         DATE,
  estado_registro               CHAR(1) not null
)

;
comment on table inv_db.SEG_PERMISOS_T
  is 'Catálogo de permisos del sistema'
;
comment on column inv_db.SEG_PERMISOS_T.id_permiso
  is 'Id del permiso'
;
comment on column inv_db.SEG_PERMISOS_T.permiso
  is 'Descripción del permiso'
;
comment on column inv_db.SEG_PERMISOS_T.direccion_electronica
  is 'Dirección electrónica de la página'
;
comment on column inv_db.SEG_PERMISOS_T.icono
  is 'Código del ícono gráfico que renderiza la seccion, ver https://fonts.google.com/icons?icon.style=Rounded'
;
comment on column inv_db.SEG_PERMISOS_T.secuencia
  is 'Orden secuencial en que se renderiza'
;
comment on column inv_db.SEG_PERMISOS_T.id_seccion
  is 'Id de la sección del menú a la que pertenece'
;
comment on column inv_db.SEG_PERMISOS_T.agregado_por
  is 'Id del usuario que agregó el registro'
;
comment on column inv_db.SEG_PERMISOS_T.agregado_en
  is 'Fecha en que se agregó el registro'
;
comment on column inv_db.SEG_PERMISOS_T.modificado_por
  is 'Último usuario que modificó el registro'
;
comment on column inv_db.SEG_PERMISOS_T.modificado_en
  is 'Última fecha de modificación del registro'
;
comment on column inv_db.SEG_PERMISOS_T.estado_registro
  is 'Estado del registro: A=Activo,I=Inactivo'
;
alter table inv_db.SEG_PERMISOS_T
  add constraint PK_SEG_PERMISOS_T_ID primary key (ID_PERMISO)
;
alter table inv_db.SEG_PERMISOS_T
  add constraint UN_SEG_PERMISOS_T_PERMISO unique (PERMISO)
;
alter table inv_db.SEG_PERMISOS_T
  add constraint FK_SEG_PERMISOS_T_SEC foreign key (ID_SECCION)
  references inv_db.SEG_SECCIONES_T (ID_SECCION)
;
alter table inv_db.SEG_PERMISOS_T
  add constraint CK_SEG_PERMISOS_T_ESTATUS
  check (estado_registro in('A','I'))
;

